"""empty message

Revision ID: 195d34c4ebd4
Revises: f4576ab5ed95
Create Date: 2025-11-19 14:30:46.394280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195d34c4ebd4'
down_revision: Union[str, Sequence[str], None] = 'f4576ab5ed95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('loans_book_id_fkey'), 'loans', type_='foreignkey')
    op.create_foreign_key(None, 'loans', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.create_foreign_key(op.f('loans_book_id_fkey'), 'loans', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
