"""add_book_edition

Revision ID: a7ee84a40c1e
Revises: b77e0a842d00
Create Date: 2025-11-19 14:44:32.790187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ee84a40c1e'
down_revision: Union[str, Sequence[str], None] = 'b77e0a842d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('edition', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'edition')
    # ### end Alembic commands ###
