"""empty message

Revision ID: f4576ab5ed95
Revises: 5c3b419954c7
Create Date: 2025-11-19 14:09:56.946550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4576ab5ed95'
down_revision: Union[str, Sequence[str], None] = '5c3b419954c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publication_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'publication_year')
    # ### end Alembic commands ###
